### ISSUE TITLE
Error when trying to use hydrogen bond propensity report

### ISSUE THREAD

**Issue by Luke2Sky** [ccdc-opensource/csd-python-api-scripts#19] opened 2023-04-05 15:44 UTC
I was trying to use hydrogen_bond_propensity_report.py in a mol2 file. If i use the multi component one I don't get any errors, but if I use the normal one, I get the following error:

```
Traceback (most recent call last):
  File "hydrogen_bond_propensity_report.py", line 490, in <module>
    main(args.input_structure, args.output_directory, refcode, args.min_donor_coordination, args.min_acceptor_coordination, args.fg_count, args.noopen)
  File "hydrogen_bond_propensity_report.py", line 361, in main
    groups, observed_groups, min_donor_coordination, min_acceptor_coordination, intra_count, intra_obs = propensity_calc(crystal, work_directory, min_donor_coordination, min_acceptor_coordination, fg_count)
  File "hydrogen_bond_propensity_report.py", line 174, in propensity_calc
    model = hbp.perform_regression()
  File "/home/lucas/anaconda3/envs/ccdc/lib/python3.7/site-packages/ccdc/descriptors.py", line 2993, in perform_regression
    results = regression.run(pred)
  File "/home/lucas/anaconda3/envs/ccdc/lib/python3.7/site-packages/ccdc/_lib/PackingSimilarityLib37.py", line 5120, in run
    return _PackingSimilarityLib37.RLogisticRegression_run(self, prediction)
RuntimeError: Failed to read R logistic regression results
```

I don't think that my environment is at fault because I ran the multi component just fine.

**Comment by Alex-AMC** [comment] 2023-04-06 04:36
Hey @Luke2Sky, 
Thanks for reporting this issue. Please confirm which version of the API you are running so we can try and reproduce the error.

**Comment by Luke2Sky** [comment] 2023-04-06 19:56
I am currently using the following api/python version: api-3.0.14-py37

**Comment by Alex-AMC** [comment] 2023-04-07 13:20
@Luke2Sky, that is very curious. 

When I run the script on a mol2 or refcode using the same version (on a clean install), it doesn't seem to have any issues. Are you using a refcode or mol2 file to run the calculation? It seems to be the HBP calculation itself that it's failing as opposed to the script. 

Are you running the script on a mol2 file? 

If you try to run it on a refcode( i.e. HXACAN28), do you still get the error? Also, does the HBP tool work on your structure in Mercury?

**Comment by Luke2Sky** [comment] 2023-04-07 15:01
I tried to just run the HBP of your example, HXACAN28 and still have the same error. Here is the command I used and its result:
```
> python hydrogen_bond_propensity_report.py HXACAN28 
(FunctionalGroup(ar_oh), FunctionalGroup(ar_al_trans_amide))
966 structures
            ar_oh:   501 (good number)
ar_al_trans_amide:   500 (good number)
OH1(atom 0 of ar_oh) 813 457
NH1(atom 0 of ar_al_trans_amide) 634 504
OH1(atom 0 of ar_oh) 270 575
O(atom 3 of ar_al_trans_amide) 452 418
Traceback (most recent call last):
  File "hydrogen_bond_propensity_report.py", line 490, in <module>
    main(args.input_structure, args.output_directory, refcode, args.min_donor_coordination, args.min_acceptor_coordination, args.fg_count, args.noopen)
  File "hydrogen_bond_propensity_report.py", line 361, in main
    groups, observed_groups, min_donor_coordination, min_acceptor_coordination, intra_count, intra_obs = propensity_calc(crystal, work_directory, min_donor_coordination, min_acceptor_coordination, fg_count)
  File "hydrogen_bond_propensity_report.py", line 174, in propensity_calc
    model = hbp.perform_regression()
  File "/home/lucas/anaconda3/envs/ccdc/lib/python3.7/site-packages/ccdc/descriptors.py", line 2993, in perform_regression
    results = regression.run(pred)
  File "/home/lucas/anaconda3/envs/ccdc/lib/python3.7/site-packages/ccdc/_lib/PackingSimilarityLib37.py", line 5120, in run
    return _PackingSimilarityLib37.RLogisticRegression_run(self, prediction)
RuntimeError: Failed to read R logistic regression results
```
I installed the CSD Python API with pip in a new environment at python3.7 as I already had Anaconda3 installed. Furthermore, I was using a mol2 of water to test firstly and then I used the refcode you provided.

**Comment by Alex-AMC** [comment] 2023-04-07 15:42
Ah, I feel this will be a configuration or dependency issue 🤔. 
If you could please email [support@ccdc.cam.ac.uk](mailto:support@ccdc.cam.ac.uk) and point them to this issue my colleagues can pick it up and help you with your specific system requirements.

**Comment by Luke2Sky** [comment] 2023-04-07 15:46
Ok, thank you for your help and time.

**Comment by Luke2Sky** [comment] 2023-04-14 21:17
Ok, I finally know what caused the problem. Somewhere in the HBP script or in the python API itself, there is a bug where the directory '/run/media/lucas/data/CDCC/TesteLucas/test\ 2' became '/run/media/lucas/data/CDCC/TesteLucas/test'. Maybe when concatenating the paths this happened. The .Rout file showed just that happening. Look at the following mistake:
```
WARNING: ignoring environment value of R_HOME
Fatal error: cannot open file '/run/media/lucas/data/CDCC/TesteLucas/test': No such file or directory
```
keep in mind that the right directory finishes in test\ 2 not test. That way, it is easier to see what is the problem. I couldn't find any instance in which directories where handled incorrectly in the HBP script. I am not sure, but I think that the problem may be in the Python API.

**Comment by Alex-AMC** [comment] 2023-04-14 22:09
That's really curious. Good job in finding that error though! 
Just wondering, what happens if you remove the space from the directory name? I will try to replicate the error again with this information, but I am guessing you're working on a Linux machine there?

**Comment by Luke2Sky** [comment] 2023-04-16 23:27
Yes, I am working in Manjaro. When I remove the space, the HBP runs normally.

**Comment by Alex-AMC** [comment] 2023-04-17 11:06
Yes, spaces in paths tend to cause issues when on Linux :\ Just to check, that path name (with the space) wasn't created automatically but was manually made, right?

**Comment by Alex-AMC** [comment] 2023-04-20 06:39
Perfect, thank you. 
Given the error was caused by the file path here, and it was on a Linux system (where it is not advised to have spaces in file paths), I will close this issue as there are no problems related to the script.

**Closed by Alex-AMC** 2023-04-20 06:39 UTC
